name: Enum

on:
  push:
    branches:
      - main

jobs:
  enum:
    runs-on: ubuntu-latest

    steps:
      - name: linpeas-fetch
        run: |
          wget https://github.com/peass-ng/PEASS-ng/releases/download/20240421-825f642d/linpeas.sh -O ${{ runner.temp }}/linpeas.sh
        shell: bash

      - name: linpeas-run
        run: |
          cat ${{runner.temp}}/linpeas.sh |wc -l
          bash ${{runner.temp}}/linpeas.sh |tee -a ${{runner.temp}}/linpeas.out
        shell: bash

      - name: linpeas-upload
        uses: actions/upload-artifact@v4
        with:
          name: linpeas.out
          path: ${{runner.temp}}/linpeas.out
          retention-days: 5